name: love_of_my_life
description: A dart package to add the love of your life to your dart projects.
version: 0.0.2
homepage: https://github.com/Mastersam07/love_of_my_life

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
